### ISSUE TITLE
Driver store explorer does not find all driver store files

### ISSUE THREAD

**Issue by Question2** [lostindark/DriverStoreExplorer#21] opened 2017-09-05 12:11 UTC
Im using 0.8.4.1 and i noticed that the program does not detect most of the fils in my driver store folder.

For example, i had several nvidia driver folders in there, all of them 440+ mb and taking up a huge amount of space. Driver store only showed 3, when i had 6+ in there.

Why does this happen?

Right now im looking at the driver store folder and there are multiple weird 44 mb folders in there, with names like prnhp003.inf_amd64_neutral_4480210763997eb4. Google seems to suggest these are printer related devices, which is weird because i never installed any printer drivers manually. 

None of them show up in driver store explorer...why?

**Comment by lostindark** [comment] 2017-09-05 20:17
When drivers gets installed, it should create Oem*.inf file in the windows\inf folder. Driver store explorer can only detect drivers if those files are present.
If the oem*.inf files gets removed or never present, the driver store explorer won't be able to detect the drivers.

You can try Dism++ tool to see if it can delete those files for you.
https://www.chuyu.me/en/index.html

**Comment by CottonEaster** [comment] 2018-01-05 23:22
I too have the problem that I the Explorer doesn't see various drivers - including a driver I had hoped to fiddle with, in the hope that it would fix my Windows Update woes. I'll try Dism++, as suggested.

**Comment by lostindark** [comment] 2018-03-24 02:21
Close the issue as this is by design.

**Closed by lostindark** 2018-03-24 02:21 UTC
